# Generated by Django 6.1 on 2026-01-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('material', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, help_text='e.g. S, M, L, XL', max_length=100)),
                ('color', models.CharField(blank=True, help_text='e.g. Red, Blue', max_length=100)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
