# Generated by Django 6.1 on 2026-01-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_theme', models.CharField(choices=[('default', 'Default (Clean/Editorial)'), ('ramadhan', 'Ramadhan (Green/Gold)'), ('christmas', 'Christmas (Red/Green)'), ('imlek', 'Imlek (Red/Gold)')], default='default', max_length=20)),
            ],
        ),
    ]
