# Generated by Django 6.1 on 2026-01-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], default='Unisex', max_length=10),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='active_theme',
            field=models.CharField(choices=[('default', 'Default (Clean/Editorial)')], default='default', max_length=20),
        ),
    ]
