# Generated by Django 6.1 on 2026-01-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_product_gender_alter_siteconfig_active_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Sweater', 'Sweater'), ('Cardigan', 'Cardigan'), ('Inner', 'Inner'), ('Polo', 'Polo')], default='Sweater', max_length=20),
        ),
    ]
